language: php

php:
  - 5.3

env:
  global:
    - "HOST=host"
    - "SSHKEY=sshkey"

matrix:
  fast_finish: true

before_install:
  - echo $host
  - echo -e $sshkey
  - mkdir .ssh
  - chmod 700 .ssh

script: echo $host

