language: php

php:
  - 5.3

env:
  global:
    - "HOST=host"
    - "SSH_KEY=sshkey"

matrix:
  fast_finish: true

before_install:
  - echo $HOST
  - mkdir .ssh
  - chmod 700 .ssh
  - echo $SSH_KEY>.ssh/id_rsa
  - chmod 600 .ssh/id_rsa

script: ssh $HOST "ls"

