language: php

php:
  - 5.3

env:
  global:
    - "HOST=host"
    - "SSHKEY=sshkey"

matrix:
  fast_finish: true

before_install:
  - mkdir .ssh
  - chmod 700 .ssh
  - echo -e $sshkey > .ssh/id_rsa
  - chmod 600 .ssh/id_rsa
  - ssh-agent -s
  - ssh-add .ssh/id_rsa

script: echo "Deploy"

after_success:
  - ssh -o StrictHostKeyChecking=no $host "ls"
